from django.core.management import BaseCommand

from sacco.models import Customer


class Command(BaseCommand):
    def handle(self, *args, **options):
        customers = [{"first_name":"Tallie","last_name":"Phippin","email":"tphippin0@reference.com","gender":"Male","dob":"2000-08-01"},
{"first_name":"Katine","last_name":"Cannop","email":"kcannop1@army.mil","gender":"Female","dob":"2003-05-01"},
{"first_name":"Archer","last_name":"Gateshill","email":"agateshill2@unblog.fr","gender":"Male","dob":"2003-11-27"},
{"first_name":"Ax","last_name":"McNay","email":"amcnay3@ibm.com","gender":"Male","dob":"2000-09-03"},
{"first_name":"Jeth","last_name":"Wylder","email":"jwylder4@blinklist.com","gender":"Male","dob":"2001-05-11"},
{"first_name":"Shandy","last_name":"Llewellyn","email":"sllewellyn5@etsy.com","gender":"Female","dob":"1999-05-07"},
{"first_name":"Ami","last_name":"Pendock","email":"apendock6@plala.or.jp","gender":"Female","dob":"2004-11-16"},
{"first_name":"Cathi","last_name":"Limmer","email":"climmer7@icq.com","gender":"Female","dob":"2000-09-14"},
{"first_name":"Diannne","last_name":"Wycherley","email":"dwycherley8@vkontakte.ru","gender":"Female","dob":"2003-07-09"},
{"first_name":"Donielle","last_name":"Govan","email":"dgovan9@loc.gov","gender":"Female","dob":"2000-07-12"},
{"first_name":"Lorenzo","last_name":"Macro","email":"lmacroa@geocities.com","gender":"Male","dob":"2003-12-05"},
{"first_name":"Carlie","last_name":"O'Dreain","email":"codreainb@skyrock.com","gender":"Male","dob":"2002-11-24"},
{"first_name":"Kipp","last_name":"Trusler","email":"ktruslerc@pinterest.com","gender":"Female","dob":"2000-05-12"},
{"first_name":"Rabi","last_name":"Alpine","email":"ralpined@sciencedaily.com","gender":"Male","dob":"2004-08-22"},
{"first_name":"Barton","last_name":"Anfosso","email":"banfossoe@yellowpages.com","gender":"Male","dob":"2001-07-18"},
{"first_name":"Igor","last_name":"Sellen","email":"isellenf@google.com","gender":"Male","dob":"2003-11-04"},
{"first_name":"Montgomery","last_name":"Cheesworth","email":"mcheesworthg@mtv.com","gender":"Male","dob":"2000-10-24"},
{"first_name":"Oren","last_name":"Trudgian","email":"otrudgianh@state.gov","gender":"Male","dob":"2000-01-27"},
{"first_name":"Aveline","last_name":"Retallick","email":"aretallicki@yahoo.com","gender":"Female","dob":"2002-08-26"},
{"first_name":"Valida","last_name":"Redler","email":"vredlerj@bloglovin.com","gender":"Female","dob":"2001-11-09"},
{"first_name":"Wolfgang","last_name":"Cobelli","email":"wcobellik@admin.ch","gender":"Male","dob":"2002-04-04"},
{"first_name":"Sasha","last_name":"Gierhard","email":"sgierhardl@go.com","gender":"Male","dob":"1999-08-28"},
{"first_name":"Terencio","last_name":"Pruce","email":"tprucem@homestead.com","gender":"Male","dob":"2003-11-14"},
{"first_name":"Lila","last_name":"Ingrey","email":"lingreyn@gmpg.org","gender":"Female","dob":"1999-01-14"},
{"first_name":"Nona","last_name":"Wadsworth","email":"nwadswortho@ucsd.edu","gender":"Female","dob":"1998-12-07"},
{"first_name":"Kanya","last_name":"Navarro","email":"knavarrop@examiner.com","gender":"Female","dob":"2000-06-04"},
{"first_name":"Consuelo","last_name":"Loughran","email":"cloughranq@latimes.com","gender":"Female","dob":"2000-04-17"},
{"first_name":"Kenneth","last_name":"Farrant","email":"kfarrantr@google.com.au","gender":"Male","dob":"2002-06-10"},
{"first_name":"Prinz","last_name":"Simoes","email":"psimoess@msu.edu","gender":"Male","dob":"1999-03-29"},
{"first_name":"Ricard","last_name":"Bleasby","email":"rbleasbyt@blogtalkradio.com","gender":"Male","dob":"1999-12-21"},
{"first_name":"Westleigh","last_name":"Ovendale","email":"wovendaleu@1688.com","gender":"Male","dob":"1998-12-13"},
{"first_name":"Kendra","last_name":"Cluckie","email":"kcluckiev@intel.com","gender":"Female","dob":"2001-09-28"},
{"first_name":"Coraline","last_name":"Hintzer","email":"chintzerw@economist.com","gender":"Female","dob":"2000-01-10"},
{"first_name":"Isidora","last_name":"Beedham","email":"ibeedhamx@microsoft.com","gender":"Female","dob":"1999-09-03"},
{"first_name":"Waverley","last_name":"Cowdroy","email":"wcowdroyy@arizona.edu","gender":"Male","dob":"1999-12-01"},
{"first_name":"Roanne","last_name":"Middiff","email":"rmiddiffz@imdb.com","gender":"Female","dob":"2000-11-18"},
{"first_name":"Freida","last_name":"Guyver","email":"fguyver10@usa.gov","gender":"Female","dob":"2000-10-09"},
{"first_name":"Tandie","last_name":"Hallaways","email":"thallaways11@paypal.com","gender":"Female","dob":"2001-11-08"},
{"first_name":"Christiana","last_name":"Creek","email":"ccreek12@altervista.org","gender":"Female","dob":"1999-02-07"},
{"first_name":"Daune","last_name":"O'Dreain","email":"dodreain13@reference.com","gender":"Female","dob":"2001-10-24"},
{"first_name":"Carter","last_name":"Nerney","email":"cnerney14@creativecommons.org","gender":"Male","dob":"1998-12-11"},
{"first_name":"Colman","last_name":"Wraggs","email":"cwraggs15@live.com","gender":"Male","dob":"2002-07-15"},
{"first_name":"Timoteo","last_name":"Romushkin","email":"tromushkin16@vk.com","gender":"Male","dob":"2000-08-08"},
{"first_name":"Darlene","last_name":"Prescote","email":"dprescote17@noaa.gov","gender":"Female","dob":"2000-05-31"},
{"first_name":"Justinn","last_name":"Dewdney","email":"jdewdney18@accuweather.com","gender":"Female","dob":"1999-07-03"},
{"first_name":"Shayne","last_name":"MacComiskey","email":"smaccomiskey19@barnesandnoble.com","gender":"Female","dob":"2004-05-23"},
{"first_name":"Tami","last_name":"Piesing","email":"tpiesing1a@aboutads.info","gender":"Female","dob":"2003-06-24"},
{"first_name":"Alie","last_name":"Piller","email":"apiller1b@reddit.com","gender":"Female","dob":"1998-12-14"},
{"first_name":"Brunhilde","last_name":"Stidston","email":"bstidston1c@kickstarter.com","gender":"Female","dob":"2001-01-23"},
{"first_name":"Brook","last_name":"Baddeley","email":"bbaddeley1d@oracle.com","gender":"Male","dob":"2001-08-01"},
{"first_name":"Heddi","last_name":"Lars","email":"hlars1e@gizmodo.com","gender":"Female","dob":"1999-01-18"},
{"first_name":"Joshuah","last_name":"Egdell","email":"jegdell1f@tinyurl.com","gender":"Male","dob":"1999-01-21"},
{"first_name":"West","last_name":"Lealle","email":"wlealle1g@seattletimes.com","gender":"Male","dob":"2000-07-17"},
{"first_name":"Nerti","last_name":"Giovanitti","email":"ngiovanitti1h@bbb.org","gender":"Female","dob":"2000-05-12"},
{"first_name":"Melisande","last_name":"Uwins","email":"muwins1i@over-blog.com","gender":"Female","dob":"2004-07-21"},
{"first_name":"Alvie","last_name":"Barford","email":"abarford1j@netlog.com","gender":"Male","dob":"2003-12-16"},
{"first_name":"Reta","last_name":"Martland","email":"rmartland1k@bbc.co.uk","gender":"Female","dob":"2001-01-06"},
{"first_name":"Bevon","last_name":"Laycock","email":"blaycock1l@linkedin.com","gender":"Male","dob":"1999-01-23"},
{"first_name":"Erwin","last_name":"Staniland","email":"estaniland1m@google.pl","gender":"Male","dob":"2003-10-24"},
{"first_name":"Terencio","last_name":"Drance","email":"tdrance1n@washingtonpost.com","gender":"Male","dob":"2004-09-27"},
{"first_name":"Letta","last_name":"Rawlingson","email":"lrawlingson1o@walmart.com","gender":"Female","dob":"2003-07-30"},
{"first_name":"Kylila","last_name":"Abbie","email":"kabbie1p@odnoklassniki.ru","gender":"Female","dob":"2000-12-31"},
{"first_name":"Chevalier","last_name":"Cone","email":"ccone1q@clickbank.net","gender":"Male","dob":"1999-07-23"},
{"first_name":"Maye","last_name":"Bexon","email":"mbexon1r@photobucket.com","gender":"Female","dob":"2004-08-16"},
{"first_name":"Brockie","last_name":"Patillo","email":"bpatillo1s@google.com","gender":"Male","dob":"2001-09-10"},
{"first_name":"Meggi","last_name":"Brunstan","email":"mbrunstan1t@parallels.com","gender":"Female","dob":"1998-12-27"},
{"first_name":"Kennett","last_name":"Goaks","email":"kgoaks1u@cbslocal.com","gender":"Male","dob":"2000-11-26"},
{"first_name":"Lannie","last_name":"Stockford","email":"lstockford1v@ehow.com","gender":"Male","dob":"2004-08-03"},
{"first_name":"Miles","last_name":"Fibbens","email":"mfibbens1w@abc.net.au","gender":"Male","dob":"2003-08-15"},
{"first_name":"Dedie","last_name":"Fownes","email":"dfownes1x@ameblo.jp","gender":"Female","dob":"1999-10-27"},
{"first_name":"Findlay","last_name":"Boxe","email":"fboxe1y@sina.com.cn","gender":"Male","dob":"1999-01-02"},
{"first_name":"Ainsley","last_name":"Chaize","email":"achaize1z@wikispaces.com","gender":"Female","dob":"2002-10-03"},
{"first_name":"Ralf","last_name":"Pietroni","email":"rpietroni20@posterous.com","gender":"Male","dob":"2004-08-20"},
{"first_name":"Laurette","last_name":"Horsell","email":"lhorsell21@intel.com","gender":"Female","dob":"2003-02-27"},
{"first_name":"Reynold","last_name":"Dickons","email":"rdickons22@hibu.com","gender":"Male","dob":"1999-04-09"},
{"first_name":"Guglielmo","last_name":"Hatchett","email":"ghatchett23@virginia.edu","gender":"Male","dob":"2000-03-20"},
{"first_name":"Gabrila","last_name":"Howells","email":"ghowells24@imdb.com","gender":"Female","dob":"1999-10-27"},
{"first_name":"Augie","last_name":"Halkyard","email":"ahalkyard25@goodreads.com","gender":"Male","dob":"2003-09-16"},
{"first_name":"Anita","last_name":"Gunton","email":"agunton26@jimdo.com","gender":"Female","dob":"1999-12-22"},
{"first_name":"Bernardine","last_name":"Matterface","email":"bmatterface27@dmoz.org","gender":"Female","dob":"1999-06-17"},
{"first_name":"Lucais","last_name":"MacCaffrey","email":"lmaccaffrey28@liveinternet.ru","gender":"Male","dob":"2004-03-17"},
{"first_name":"Stephannie","last_name":"Rowcastle","email":"srowcastle29@unicef.org","gender":"Female","dob":"2001-08-21"},
{"first_name":"Pascale","last_name":"Fittall","email":"pfittall2a@howstuffworks.com","gender":"Male","dob":"2003-12-18"},
{"first_name":"Sharai","last_name":"Petroff","email":"spetroff2b@mtv.com","gender":"Female","dob":"2001-06-12"},
{"first_name":"Kimmi","last_name":"Edmondson","email":"kedmondson2c@mashable.com","gender":"Female","dob":"2001-02-07"},
{"first_name":"Brittaney","last_name":"Jagiela","email":"bjagiela2d@dailymotion.com","gender":"Female","dob":"2001-07-30"},
{"first_name":"Ashby","last_name":"Kleinert","email":"akleinert2e@latimes.com","gender":"Male","dob":"2001-01-04"},
{"first_name":"Meggie","last_name":"Heigho","email":"mheigho2f@quantcast.com","gender":"Female","dob":"2004-03-30"},
{"first_name":"Baxter","last_name":"Wildt","email":"bwildt2g@amazon.de","gender":"Male","dob":"2003-01-12"},
{"first_name":"Reinaldo","last_name":"Milesap","email":"rmilesap2h@mozilla.com","gender":"Male","dob":"2001-11-27"},
{"first_name":"Audry","last_name":"Cornuau","email":"acornuau2i@aol.com","gender":"Female","dob":"2001-10-31"},
{"first_name":"Isak","last_name":"Tort","email":"itort2j@boston.com","gender":"Male","dob":"2001-04-10"},
{"first_name":"Fan","last_name":"Pennigar","email":"fpennigar2k@multiply.com","gender":"Female","dob":"2002-10-31"},
{"first_name":"Deloria","last_name":"Monery","email":"dmonery2l@jigsy.com","gender":"Female","dob":"2003-12-28"},
{"first_name":"Ripley","last_name":"Edel","email":"redel2m@smugmug.com","gender":"Male","dob":"2003-09-17"},
{"first_name":"Franklin","last_name":"Lemon","email":"flemon2n@baidu.com","gender":"Male","dob":"2004-02-26"},
{"first_name":"Zebulon","last_name":"Lugard","email":"zlugard2o@sina.com.cn","gender":"Male","dob":"1999-04-01"},
{"first_name":"Mella","last_name":"Wonter","email":"mwonter2p@rambler.ru","gender":"Female","dob":"2000-02-07"},
{"first_name":"Casandra","last_name":"Radmer","email":"cradmer2q@delicious.com","gender":"Female","dob":"2002-01-04"},
{"first_name":"Fayina","last_name":"Vesque","email":"fvesque2r@weibo.com","gender":"Female","dob":"2004-08-25"}]
        for c in customers:
            customer = Customer(**c)
            customer.save()

        print("Populated customers successfully")
        # python manage.py populate